#baseurl = "https://gitee.com/tjopenlab/como-grammar-manual/Introduction_to_Programming_with_COMO/public/"
baseurl = "file:///E:/UbuntuHome/como-grammar-manual/Introduction_to_Programming_with_COMO/public/"

#baseurl = "/t_o_n_g_j_i/"
# 如果不是自己手动写 目录菜单：
# 由于Hugo在处理非根URL（如：http://www.tongji.edu.cn/path/）时有bug，所以在通过下面的命令生成静态文件后，
# hugo_extended_0.81.0_Linux-64bit/hugo -D
# 需要把 public 目录下的所有文件中的 /t_o_n_g_j_i 替换为真正的URL, 如：
# file:///E:/UbuntuHome/como-grammar-manual/Introduction_to_Programming_with_COMO/public
#

languageCode = "zh-CN"
title = "COMO程序设计"
theme = "book"

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable "Last Modified by" date and git author
#  information on "doc" type pages.
enableGitInfo = true

[params]
    # Set source repository location.
    # Used for "Last Modified" and "Edit this page" links.
    BookRepo = "https://gitee.com/tjopenlab/como-grammar-manual/"

    # Enable "Edit this page" links for "doc" page type.
    # Disabled by default. Uncomment to enable. Requires "BookRepo" param.
    # Path must point to the site directory.
    BookEditPath = "Introduction_to_Programming_with_COMO"

    # (Optional, default January 2, 2006) Configure the date format used on the pages
    # - In git information
    # - In blog posts
    BookDateFormat = "2006 January 2"

    # (Optional, default none) Set leaf bundle to render as side menu
    # When not specified file structure and weights will be used
    BookMenuBundle = "/menu"
